import React from "react";
import { Bar, Benefit1, Benefit2, Benefit3, Constellation, Constellation2, Constellation3 } from "../assets/Minting/assets";
import Button from "./Button";
const Benefits = () => {
  return (
    <>
      <div className="-mt-80">
        
        <div className="">
        
        <div className="relative left-0 z-10 top-80">
          <img src={Constellation} alt="" />
        </div>
          <h2 className="font-Bakbak mx-[30%]  text-4xl relative z-10 top-24">
            Benefits
          </h2>
          
          <img src={Bar} alt="" className="" />
          <div className="absolute -right-4 -mt-60">
          <img src={Constellation2} alt="" />
        </div>
        </div>
        <div className="mx-[15%]  ">
          <div className="flex justify-between">
            <div className="w-1/2 mt-[20%]">
              <h2 className="font-Urbanist text-2xl font-bold text-violet uppercase">
                Enjoy Trading Fees dividends
              </h2>
              <p className="mb-8 font-Inter text-lg mt-3">
                Enjoy 10% dividends of the trading fees generated by <br />{" "}
                eruSwap, claimable on a weekly basis
              </p>
              <Button text="CONNECT WALLET"></Button>
            </div>
            <div className="w-1/2 mt-20 ml-10 px-10">
              {" "}
              <img src={Benefit1} alt="" className="h-84" />
            </div>
          </div>
          <div className="flex justify-between">
            <div className="w-1/2 py-10 -mt-8 pr-8 mr-10">
              {" "}
              <img src={Benefit2} alt="" className="h-80" />
            </div>
            <div className="w-1/2 mt-[10%]">
              <h2 className="font-Urbanist text-2xl font-bold text-violet uppercase">
              Governance token airdrop
              </h2>
              <p className="mb-8 font-Inter text-lg mt-3">
              ERU CHEFS holder receive a free airdrop of governance token after the TGE
              </p>
             
            </div>
          </div>
          <div className="flex justify-between">
            <div className="w-1/2 my-[15%]">
              <h2 className="font-Urbanist text-2xl font-bold text-violet uppercase">
                DAO governance qualification
              </h2>
              <p className="mb-8 font-Inter text-lg mt-3">
                ERU CHEFS holder will participate in the DAO governance of the
                entire eruSwap ecology with voting and proposal rights
              </p>
            
            </div>
            <div className="w-1/2  ml-10 px-10">
              {" "}
              <img src={Benefit3} alt="" className="h-84" />
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Benefits;
