import React from "react";
import {
  Bar,
  Benefit1,
  Benefit2,
  Benefit3,
  Constellation,
  Constellation2,
  Stakingbenefits,
  Earning,
  Shapes2,
} from "../assets/Minting/assets";
import Button from "./Button";
const Benefits = () => {
  return (
    <>
      <div className="-mt-80">
        <div className="">
          <div className="relative left-0 z-10 top-80">
            <img src={Constellation} alt="" />
          </div>
          <h2 className="font-Bakbak mx-[30%]  text-4xl relative z-10 top-24">
            Benefits
          </h2>

          <img src={Bar} alt="" className="" />
          <div className="absolute right-0 -mt-60">
            <img src={Constellation2} alt="" />
          </div>
        </div>
        <div className="mx-[10%] text-text-field ">
          <div className="flex justify-between">
            <div className="w-1/2 mt-[20%]">
              <h2 className="font-Urbanist text-2xl font-bold text-violet uppercase">
                Enjoy Trading Fees dividends
              </h2>
              <p className="mb-8 font-Inter text-lg mt-3">
                Enjoy 10% dividends of the trading fees generated by 
                eruSwap, claimable on a weekly basis
              </p>
              
            </div>
            <div className="w-1/2 mt-20 ml-10 px-10">
              {" "}
              <img src={Benefit1} alt="" className="h-84" />
            </div>
          </div>
          <div className="flex justify-between items-center">
            <div className="w-1/2 py-10 -mt-8 pr-8 mr-10">
              <img src={Stakingbenefits} alt="" className=" w-full" />
            </div>
            <div className="w-1/2 mt-[10%]">
              <h2 className="font-Urbanist text-2xl font-bold text-violet uppercase">
                EARN ROYALTIES
              </h2>
              <p className="mb-8 font-Inter text-lg mt-3 text-text-field">
                ERU CHEFS stakers share the 1% royalty from secondary sales and
                other marketplaces.
              </p>
            </div>
          </div>
          <div className="absolute right-0 -mt-64 h-1/2">
            <img src={Shapes2} alt="" className="h-full" />
          </div>
          <div className="flex justify-between">
            <div className="w-1/2 my-[10%]">
              <h2 className="font-Urbanist text-2xl font-bold text-violet uppercase">
                DAO governance qualification
              </h2>
              <p className="mb-8 font-Inter text-lg mt-3">
                ERU CHEFS holder will participate in the DAO governance of the
                entire eruSwap ecology with voting and proposal rights
              </p>
            </div>
            <div className="w-1/2  ml-10 px-10">
              {" "}
              <img src={Benefit3} alt="" className="h-84" />
            </div>
          </div>
          <div className="flex justify-between">
            <div className="w-1/2 py-10 -mt-8 pr-8 mr-10">
              <img src={Benefit2} alt="" className="h-80" />
            </div>
            <div className="w-1/2 mt-[10%]">
              <h2 className="font-Urbanist text-2xl font-bold text-violet uppercase">
                Governance token airdrop
              </h2>
              <p className="mb-8 font-Inter text-lg mt-3">
                ERU CHEFS holder receive a free airdrop of governance token
                after the TGE
              </p>
            </div>
          </div>
          <div className="flex justify-between">
            <div className="w-1/2 my-[10%]">
              <h2 className="font-Urbanist text-2xl font-bold text-violet uppercase">
                ERU CHEFS Minter Royalties
              </h2>
              <p className="mb-8 font-Inter text-lg mt-3">
                The original minters of the 3000 ERU CHEFS NFTs earn 2% from the
                secondary sales of ERU CHEFS NFTs, seeded to the **ERU CHEFS
                Minter Royalties** pool weekly.
              </p>
            </div>
            <div className="w-1/2  ml-10 px-10 flex justify-center">
              {" "}
              <img src={Earning} alt="" className="h-3/4" />
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Benefits;
